In [ ]:
import gym
import numpy as np
import random

In [ ]:
env = gym.make('FrozenLake-v0')
env.render()


SFFF
FHFH
FFFH
HFFG


In [ ]:
state_size=env.observation_space.n
action_size=env.action_space.n
print(state_size)
print(action_size)

16
4


In [ ]:
qtable=np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
total_episodes=20000
max_steps=100
alpha=0.8
gamma=0.90
epsilon=0.8

In [ ]:
for episode in range(total_episodes):
  state=env.reset()
  reward=0
  total_rewards=0
  for step in range(max_steps):
    if random.uniform(0,1)>epsilon:
      action=np.argmax(qtable[state,:])
    else:
      action=env.action_space.sample()
    
    new_state,reward,done,info=env.step(action)
    qtable[state, action] = qtable[state, action] + alpha * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])

    total_rewards+=reward
    state=new_state

    if done==True:
      break
print(qtable)

[[0.28681739 0.28381309 0.32348022 0.29218989]
 [0.25705964 0.24848883 0.27786607 0.41141272]
 [0.49360481 0.26282487 0.27002067 0.28422963]
 [0.28879658 0.17147311 0.01037537 0.24978857]
 [0.34935411 0.07658259 0.07540234 0.25987082]
 [0.         0.         0.         0.        ]
 [0.39748166 0.65358728 0.52494833 0.03796535]
 [0.         0.         0.         0.        ]
 [0.06673159 0.08790947 0.34017708 0.42444871]
 [0.09718888 0.46454048 0.41706961 0.09478101]
 [0.57585835 0.0244925  0.14245433 0.36778039]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44617227 0.14685962 0.55982482 0.7332426 ]
 [0.64229181 0.88035377 0.98613055 0.7679467 ]
 [0.         0.         0.         0.        ]]


In [ ]:
env.reset()
for episode in range(5):
  state=env.reset()
  step=0
  done=False
  print('********************')
  print('EPISODE',episode)

  for step in range(max_steps):
    action=np.argmax(qtable[state,:])
    new_state,reward,done,info=env.step(action)
    if done:
      env.render()
      if new_state==15:
        print('Reached')
      else:
        print('Hole')
      print('No. of steps=',step) 
      break
    state=new_state
env.close()


********************
EPISODE 0
  (Left)
SFFF
FHFH
FFFH
HFFG
Hole
No. of steps= 10
********************
EPISODE 1
  (Up)
SFFF
FHFH
FFFH
HFFG
Hole
No. of steps= 97
********************
EPISODE 2
  (Down)
SFFF
FHFH
FFFH
HFFG
Reached
No. of steps= 79
********************
EPISODE 3
  (Down)
SFFF
FHFH
FFFH
HFFG
Reached
No. of steps= 65
********************
EPISODE 4
  (Left)
SFFF
FHFH
FFFH
HFFG
Hole
No. of steps= 35
